# H2 Database Ayarları (Bellek içi değil, disk tabanlı yaparak gerçek bir veritabanı simüle ediyoruz)
spring.datasource.url=jdbc:h2:file:./data/benchmarkdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Veritabanı sorgularının gerçekten çalıştığını konsolda ispatlamak için:
spring.jpa.show-sql=true

# H2 Konsolunu Aktif Etme
spring.h2.console.enabled=true

# Redis Cache Ayarları
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Uygulama Portu (8080 dolu olduğu için 8081'e alındı)
server.port=8081
